### ISSUE TITLE
Reactive code variables 

### ISSUE THREAD

**Issue by etune** [metachris/vue-highlightjs#22] opened 2018-09-12 21:12 UTC
``` html
<!-- If your source-code lives in a variable called 'sourcecode' -->
<pre v-highlightjs="sourcecode"><code class="javascript"></code></pre>
```
My `sourcecode` variable is being updated asynchronously. When it's updated, the changes aren't reflected on the page. 

Is there a way to make the directive reactive?

**Comment by sonnh58** [comment] 2018-10-25 04:48
Same issue.

**Comment by intermundos** [comment] 2018-10-28 15:25
I can confirm, same is happening in my project. 

Removing v-highlightjs directive makes code block reactive again.

**Comment by mslawins** [comment] 2018-11-25 19:08
Did any of you found solution to this problem? How to achieve reactive highlighting?

**Comment by etune** [comment] 2018-11-26 13:54
> Did any of you found solution to this problem? How to achieve reactive highlighting?

I did not, sorry.

**Comment by prune998** [comment] 2019-03-05 15:25
Not working for me either...

tried : 
```
<pre v-highlightjs> <code class="json">{{ prettySnapshot }}</code></pre>
```
where `prettySnapshot` is a computed variable and : 
```
<pre v-highlightjs=prettySnapshot> <code class="json"></code></pre>
```
with no luck...

Any chance we can use Reactive stuff with highlight.js and vuejs ?

**Comment by prune998** [comment] 2019-03-05 15:55
@metachris do you still maintain this code ?

**Comment by SkyblueMr** [comment] 2019-03-26 21:38
> Not working for me either...
> 
> tried :
> 
> ```
> <pre v-highlightjs> <code class="json">{{ prettySnapshot }}</code></pre>
> ```
> where `prettySnapshot` is a computed variable and :
> 
> ```
> <pre v-highlightjs=prettySnapshot> <code class="json"></code></pre>
> ```
> with no luck...
> 
> Any chance we can use Reactive stuff with highlight.js and vuejs ?


try:
```
<pre v-highlightjs=prettySnapshot> <code class="json" id="json"></code></pre>
```
 
by:
```
document.querySelector('#json').innerText
```
get the changed code.

**Comment by Daruse93** [comment] 2019-11-07 14:09
So no one found a normal solution? Sorry, we miss such a library (

**Comment by bramchi** [comment] 2020-02-23 09:36
Take a look at https://github.com/gluons/vue-highlight.js/. 
For me it worked with reactive variables right out of the box.

**Comment by metachris** [comment] 2021-05-24 15:55
Closing this issue because this project is officially superseded by https://github.com/highlightjs/vue-plugin

Thanks for participating <3

**Closed as completed by metachris** 2021-05-24 15:55 UTC
