### ISSUE TITLE
Vue components compile inside the highlightjs block

### ISSUE THREAD

**Issue by absolutehype** [metachris/vue-highlightjs#13] opened 2017-10-25 17:19 UTC
I'm trying to use highlightjs to display code samples for some Bootstrap Vue components, however these seem to get rendered in place.

I've tried adding [v-pre](https://vuejs.org/v2/api/#v-pre) to the component but it still seems to render. Does anyone know of a workaround?

```html
<pre v-highlightjs>
	<code class="javascript">
		const s = new Date().toString()
		<b-table bordered :items="items" v-pre></b-table>
	</code>
</pre>
```

This feels like something that Vue Highlight JS should handle.

**Comment by metachris** [comment] 2017-10-27 09:59
I just noticed that there is an issue, HTML tags are not properly highlighted but they disappear. Need to take a look at this.

**Comment by andredewaard** [comment] 2018-03-21 09:16
Any progress on this? Trying to do the same. import a vue component with an template, script and style tag. The problem is only the template section is highlighted but the html tags are not visible.

**Comment by metachris** [comment] 2021-05-24 15:56
Closing this issue because this project is officially superseded by https://github.com/highlightjs/vue-plugin

Thanks for participating <3

**Closed as completed by metachris** 2021-05-24 15:56 UTC
